"""Headless test harness for gbpython.

Boots gbpython.gb inside the pygameboy emulator (../../pygameboy), drives the
joypad, and reads the background tilemap back as text.

Two ways to enter a program:
  * repl(source)      -- fast path: writes the source directly into the ROM's
                         input_buffer (address from gbpython.noi), presses START.
  * type_source(text) -- real path: navigates the on-screen keyboard with the
                         d-pad and presses A per character.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

PYGAMEBOY = Path(__file__).resolve().parent.parent.parent / "pygameboy"
sys.path.insert(0, str(PYGAMEBOY))

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")

from conformance import create_headless_system  # noqa: E402
from emulator import load_rom  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
ROM = ROOT / "gbpython.gb"
NOI = ROOT / "gbpython.noi"

TILEMAP = 0x9800
SCREEN_W = 20
SCREEN_H = 18
FRAME_CYCLES = 70224

# gbdk console with font_spect: tile index == ASCII - 0x20 (font starts at
# space), inverted copies live at +128 (generated by the ROM at boot).
# Verified empirically against the splash screen text.

OSK_GRID = [
    "1234567890+-*/=",
    "qwertyuiop()<>%",
    "asdfghjkl;:'\",.",
    "zxcvbnm!?_[]{}\n",
]
OSK_COLS = len(OSK_GRID[0])
OSK_X = 2
OSK_Y = 13
OUT_TOP = 7
OUT_ROWS = 5


def load_symbols() -> dict[str, int]:
    syms = {}
    for line in NOI.read_text().splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[0] == "DEF":
            syms[parts[1]] = int(parts[2], 16)
    return syms


class GBPython:
    def __init__(self) -> None:
        self.cpu, self.mem = create_headless_system(load_rom(str(ROM)))
        self.syms = load_symbols()
        self.osk_row = 0
        self.osk_col = 0
        self.boot()

    # -- low-level -----------------------------------------------------------

    def frames(self, n: int) -> None:
        for _ in range(n):
            self.cpu.run(max_cycles=FRAME_CYCLES, realtime=False, announce=False)

    def press(self, key: str, hold: int = 2, release: int = 2) -> None:
        self.mem.joypad.set_key(key, True)
        self.frames(hold)
        self.mem.joypad.set_key(key, False)
        self.frames(release)

    def screen(self) -> list[str]:
        rows = []
        for y in range(SCREEN_H):
            row = self.mem.storage[TILEMAP + 32 * y : TILEMAP + 32 * y + SCREEN_W]
            rows.append("".join(chr((t & 0x7F) + 0x20) if (t & 0x7F) + 0x20 < 127 else " " for t in row))
        return rows

    def screen_text(self) -> str:
        return "\n".join(self.screen())

    # -- boot ----------------------------------------------------------------

    def wait_for(self, text: str, max_frames: int = 1200) -> None:
        waited = 0
        while text not in self.screen_text():
            self.frames(10)
            waited += 10
            if waited > max_frames:
                raise TimeoutError(f"{text!r} never appeared:\n{self.screen_text()}")

    def boot(self) -> None:
        self.wait_for("PRESS START")  # font generation + splash draw
        self.press("start", hold=3, release=3)
        self.wait_for("REPL")  # splash wipe (2 frames/row) + REPL draw
        self.frames(10)

    # -- fast input path -----------------------------------------------------

    def inject(self, source: str) -> None:
        buf = self.syms["_input_buffer"]
        ln = self.syms["_input_len"]
        data = source.encode("ascii")
        assert len(data) < 254, "program too long for input_buffer"
        self.mem.storage[buf : buf + len(data)] = data
        self.mem.storage[buf + len(data)] = 0
        self.mem.storage[ln] = len(data)

    def wait_run_done(self, max_frames: int = 3000) -> None:
        """run_interpreter clears input_len when it finishes."""
        ln = self.syms["_input_len"]
        waited = 0
        while self.mem.storage[ln] != 0:
            self.frames(10)
            waited += 10
            if waited > max_frames:
                raise TimeoutError("interpreter still running")

    def repl(self, source: str) -> list[str]:
        """Run source through the interpreter, return output-area lines."""
        self.inject(source)
        self.press("start", hold=3, release=3)
        self.wait_run_done()
        self.frames(5)
        out_rows = self.screen()[OUT_TOP : OUT_TOP + OUT_ROWS]
        return [r.rstrip() for r in out_rows]

    # -- real OSK typing path --------------------------------------------------

    def _cursor(self) -> tuple[int, int]:
        return (
            self.mem.storage[self.syms["_cursor_row"]],
            self.mem.storage[self.syms["_cursor_col"]],
        )

    def move_cursor(self, ch: str) -> tuple[int, int]:
        """D-pad the OSK cursor onto ch; returns its (row, col)."""
        for r, row in enumerate(OSK_GRID):
            if ch in row:
                c = row.index(ch)
                break
        else:
            raise ValueError(f"char {ch!r} not on OSK")
        # The ROM can miss a press while redrawing the keyboard, so verify
        # each move against the cursor variables and retry until it lands.
        while self._cursor() != (r, c):
            cur_r, cur_c = self._cursor()
            if cur_r < r:
                self.press("down", hold=3, release=3)
            elif cur_r > r:
                self.press("up", hold=3, release=3)
            elif cur_c < c:
                self.press("right", hold=3, release=3)
            else:
                self.press("left", hold=3, release=3)
        return r, c

    def type_char(self, ch: str) -> None:
        buf_len = self.mem.storage[self.syms["_input_len"]]
        if ch == " ":
            # space is emitted on select release
            while self.mem.storage[self.syms["_input_len"]] == buf_len:
                self.press("select", hold=3, release=3)
            return
        if ch.isupper():
            # shift chord: hold select while pressing A
            self.move_cursor(ch.lower())
            self.mem.joypad.set_key("select", True)
            self.frames(3)
            while self.mem.storage[self.syms["_input_len"]] == buf_len:
                self.press("a_button", hold=3, release=3)
            self.mem.joypad.set_key("select", False)
            self.frames(3)
            return
        self.move_cursor(ch)
        while self.mem.storage[self.syms["_input_len"]] == buf_len:
            self.press("a_button", hold=3, release=3)

    def tile_at(self, x: int, y: int) -> int:
        """Background tilemap index at screen cell (x, y)."""
        return self.mem.storage[TILEMAP + 32 * y + x]

    def tile_data(self, index: int) -> bytes:
        """16-byte tile pixel data (gbdk console uses signed 0x8800 addressing:
        tiles 0-127 at 0x9000, tiles 128-255 at 0x8800)."""
        addr = 0x9000 + index * 16 if index < 128 else 0x8800 + (index - 128) * 16
        return bytes(self.mem.storage[addr : addr + 16])

    def type_source(self, text: str) -> None:
        for ch in text:
            self.type_char(ch)

    def screenshot(self, path: str, scale: int = 2) -> None:
        """Render the PPU frame buffer to a PNG."""
        import numpy as np
        import pygame

        shades = np.asarray(self.mem.video.frame_buffer, dtype=np.uint8).reshape(144, 160)
        # DMG-ish palette, light to dark
        palette = np.array(
            [[224, 248, 208], [136, 192, 112], [52, 104, 86], [8, 24, 32]],
            dtype=np.uint8,
        )
        rgb = palette[np.clip(shades, 0, 3)]
        surf = pygame.surfarray.make_surface(rgb.swapaxes(0, 1))
        if scale != 1:
            surf = pygame.transform.scale(surf, (160 * scale, 144 * scale))
        pygame.image.save(surf, path)

    def run_typed(self) -> list[str]:
        self.press("start", hold=3, release=3)
        self.wait_run_done()
        self.frames(5)
        return [r.rstrip() for r in self.screen()[OUT_TOP : OUT_TOP + OUT_ROWS]]
